
export enum codes {
  ERR_KEYCHAIN_REQUIRED = 'ERR_KEYCHAIN_REQUIRED',
  ERR_INVALID_PARAMETERS = 'ERR_INVALID_PARAMETERS',
  ERR_INVALID_CMS = 'ERR_INVALID_CMS',
  ERR_MISSING_KEYS = 'ERR_MISSING_KEYS',
  ERR_NO_KEY = 'ERR_NO_KEY'
}
